### PR TITLE
feat: Add Template_Version to templates and instances

### PR DESCRIPTION
**Pull request by jayhawk87**
Closes: https://github.com/IBM/compliance-trestle/issues/761

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

### CODE REVIEW

**Comment by butler54** [comment]
@jayhawk87 Looking at the PR in the current state i'm slightly confused. Let me know when you are happy and good to go.

**Comment by enikonovad** [comment]
I think this PR can be now closed as changes were included to the PR https://github.com/IBM/compliance-trestle/pull/837

**Review by fsuits — COMMENTED** [review]
I agree that if these changes are fully subsumed by the PR already merged then it should be closed.

**Comment by butler54** [comment]
Closing this out based on what @enikonovad did leveraging this PR.

**Pull request closed without merging**
