### PR TITLE
feat: new format csv to oscal component definition

### PR DESCRIPTION
**Pull request by degenaro**
Signed-off-by: degenaro <lou.degenaro@gmail.com>

## Types of changes

- [ ] Hot fix (emergency fix and release)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation (change which affects the documentation site)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary

Issue #1244 .

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by degenaro** [comment]
@fsuits has looked at the property name changes and has determined those of impact to generate and/or assemble did not change. @enikonovad @vikas-agarwal76 this PR is ready for review, thx!

**Comment by degenaro** [comment]
Reclassified as breaking change.

**Review by fsuits — APPROVED** [review]
LGTM

**Comment by tabburton** [comment]
The tutorial needs to be updated.  It looks like the changes would be in the [transformation.md](https://github.com/IBM/compliance-trestle/blob/develop/docs/tutorials/task.csv-to-oscal-cd/transformation.md) and the  [ocp4-sample-input.csv](https://github.com/IBM/compliance-trestle/blob/develop/docs/tutorials/task.csv-to-oscal-cd/ocp4-sample-input.csv).  They don't represent the required columns correctly.

**Comment by degenaro** [comment]
Would you mind opening an issue for this? If you are interested in
forking & fixing that would be nice, else I can. Thx. Lou.

**Comment by tabburton** [comment]
Okay, I'll do that.  I was going to but  I thought I'd ask first.

**Pull request merged**
