### PR TITLE
fix: use empty string if prose in part is None while writing to markdown

### PR DESCRIPTION
**Pull request by srmamit**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by srmamit** [comment]
@AleJo2995 @vikas-agarwal76 PR is ready for review.
Resolves: https://github.com/IBM/compliance-trestle/issues/1391

**Review by AleJo2995 — APPROVED** [review]
LGTM. Just a quick question... Why is it the check for "Meets testing requirements" unchecked in the checks when doing the PR?

**Comment by srmamit** [comment]
Check marked `Meets testing requirements`. Initially I was not sure what those requirements would be so I left it unchecked.

**Comment by AleJo2995** [comment]
thanks @srmamit . You are good to go. Remember to squash and merge :)

**Pull request merged**
