### PR TITLE
feat: Add support for ignored fields to header

### PR DESCRIPTION
**Pull request by jayhawk87**
Specific list:
- 'extra-fields'
- 'additional-approvers'

Signed-off-by: Ryan Moats <rmoats@us.ibm.com>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

### CODE REVIEW

**Comment by butler54** [comment]
Updating branch - to review in the next few hours.

**Comment by butler54** [comment]
I think we now have some conflicts here.

@enikonovad can you verify this works on drawio as well?

**Comment by jayhawk87** [comment]
`I think we now have some conflicts here otherwise we are good to go.` Yes - I need to rebase ...

**Comment by jayhawk87** [comment]
@butler54 - now rebased and everything (sans sonar) _should_ pass

**Comment by butler54** [comment]
> @butler54 - now rebased and everything (sans sonar) _should_ pass

Will merge before it gets messed up again! Thanks!

**Pull request merged**
