### PR TITLE
Initial set of pretty badges

### PR DESCRIPTION
**Pull request by butler54**
Signed-off-by: Chris Butler <chris@thebutlers.me>

## Types of changes

- \[x\] Bug fix (non-breaking change which fixes an issue)
- \[ \] New feature (non-breaking change which adds functionality)
- \[ \] Breaking change (fix or feature that would cause existing functionality to change)
- \[ \] My code follows the code style of this project.
- \[x\] My change requires a change to the documentation.
- \[x\] I have updated the documentation accordingly.
- \[x\] I have added tests to cover my changes.
- \[x\] All new and existing tests passed.

This fixes an undiscovered issue where gen-oscal was not correctly updating off of the OSCAL repo. Due to some changes in the OSCAL repo structure there was some additional refactoring that was required.

Also: adds badges to the readme.

### CODE REVIEW

**Comment by butler54** [comment]
Happy to add more. I basically copy and pasted a few across.

**Review by brunomarq — APPROVED** [review]
LGTM

**Review by leninmehedy — APPROVED** [review]
Looks great. Thanks

**Comment by butler54** [comment]
Re-requested review as more substantial fixes were run.

**Review by fsuits — APPROVED** [review]
I see the source content has changed but it looks like fix_any has handled the changes proplerly and I don't see any conflicts.  Assuming the source changes are as intended I approve this merge.  LGTM

**Pull request merged**
