### PR TITLE
feat: remove default namespace and define generic trestle ns

### LINKED ISSUE #1211: Handling of properties namespace
## Issue description / feature objectives
Currently we use a default namespace in profile-generate to specify namespace which is added as a default namespace in yaml header, and all props having that namespace will not have namespace populated in yaml header x-trestle-add-props.

But there are some props defined by OSCAL itself such as "marking" in profile, for which no ns is specified and by default all props having no ns are assumed to be from OSCAL namespace. This will clash with the above assumption as these OSCAL defined props will now be treated as part of default ns when converting markdowns back to OSCAL.

There are couple of options -
1. for OSCAL specific props add a field called no-ns while converting JSON to markdown to explicitly specify that it has no namespace. While converting back to OSCAL such props will not have the default ns (no ns attribute).
2. don't use default namespace option in profile generate at all, and let all props have their namespace populated in yaml header, if they are populated in JSON, and vice-versa.

Option 2 is simpler as it removes the default ns completely, but all non OSCAL props will have ns attribute in YAML header which will become verbose.

Option 1 will not require populating ns value in yaml header if they match with default ns,, but for others it will have to be populated and for OSCAL props a new attribute no-ns will have to be specified.

### PR DESCRIPTION
**Pull request by fsuits**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [ ] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary
Removed default-namespace and added generic trestle namespace for display-name
Improved test coverage

closes #1211 
## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by enikonovad** [comment]
This is a breaking change for the automation on test-profiles. So I ran a sanity check on the test-profiles. Couple of issues. 

## Issues.
### Issue 1. 
This is actually related to recently closed https://github.com/IBM/compliance-trestle/issues/1212. The issue is still there.
`smt-part` gets renamed in the generated markdowns

Before
```
  - name: control_requirement_type_iii
    value: Manual, Prospectively Automated
    smt-part: ac-1_smt.b
```
After 
```
  - name: control_requirement_type_iii
    value: Manual, Prospectively Automated
    smt-part: b <--- This is wrong
```

Steps to reproduce:
1. Run `trestle author profile-generate --output md_profiles/IBM_FS_CLOUD --name IBM_FS_CLOUD` 
2. Observe the change


### Issue 2. 
After changing ns in the JSON profile, it is NOT propagated to the markdown. But I think it should be? 

Steps to reproduce:
1. Delete exsisting markdown folder.
2. `trestle author profile-generate --output md_profiles/IBM_FS_CLOUD --name IBM_FS_CLOUD` <<- all good
3. `trestle author profile-assemble --markdown md_profiles/IBM_FS_CLOUD --output IBM_FS_CLOUD --set-parameters` <<- all good
4. Go into `IBM_FS_CLOUD/profile.json` and change ANY ns to http://ibm.com
5. `trestle author profile-generate --output md_profiles/IBM_FS_CLOUD --name IBM_FS_CLOUD` <<- NO CHANGES to the markdowns
6. Try `trestle author profile-generate --output md_profiles/IBM_FS_CLOUD --name IBM_FS_CLOUD -ohv` <<- Again NO CHANGES

**Comment by fsuits** [comment]
In reviewing the implementation for -ohv, it only applies to contents coming from the yaml header.  It does not apply to contents coming from the source profile.  In a normal generate/assemble cycle they would always be in sync - but if content is re-injected from a different source profile it will only *add* sections to the body and the header contents will not be affected.  This can be changed, but it is problematic if the md has desired changes that would then get overwritten by changes in the upstream profile that have not been syncd.

**Comment by enikonovad** [comment]
LGTM - functionality wise it looks good, but as this is a breaking change, lets wait with merge

**Review by enikonovad — APPROVED** [review]
LGTM

**Pull request merged**
