### PR TITLE
fix: remove incorrect scc_check_version

### PR DESCRIPTION
**Pull request by degenaro**
## Types of changes

- \[ \] Bug fix (non-breaking change which fixes an issue)
- \[ \] New feature (non-breaking change which adds functionality)
- \[x] Breaking change (fix or feature that would cause existing functionality to change)
- \[x] My code follows the code style of this project.
- \[ \] My change requires a change to the documentation.
- \[ \] I have updated the documentation accordingly.
- \[ \] I have added tests to cover my changes.
- \[x] All new and existing tests passed.
- \[x] All commits are signed-off.

### CODE REVIEW

**Review by butler54 — CHANGES_REQUESTED** [review]
Everything looks good except the docs which are in the python directory. This will explode users install base. Make sure all docs are in the docs/ directory.

A couple of finer features:
1) Ensure that `3rd-party-schema-documents/IBM_assessment_result_interchange_SCC/README.md` is integrated, as appropriate, with the diagram.
2) Given this I'll add @vikas-agarwal76  as a reviewwer.
3) I think it would be worth converting your xlsx into a csv and then a table on the website (see here: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#images-tables-charts--graphs) If you have Q's on how to do that reach out.

**Review by vikas-agarwal76 — COMMENTED** [review]
@degenaro Earlier as per mapping xlsx file "Check ID Version" from tanium was mapping to 2 classes - "scc_check_version" and "scc_predefined_profile_version". Are we now removing the "scc_check_version" mapping and only keeping "scc_predefined_profile_version"?

Is this the main change here?

Also, in documentation you have put PVPs as - Process Verified Programs (PVPs), whereas PVP stands for Policy Validation Points. Pls. correct this.

**Comment by degenaro** [comment]
Yep, as requested by Anca.

Lou.

**Review by butler54 — APPROVED** [review]
LGTM pending renaming of PVP's in the documentation.

Generated this: https://github.com/IBM/compliance-trestle/issues/596 issue separately which requires @vikas-agarwal76's attention.

**Pull request merged**
