### PR TITLE
fix: rules at component level2

### PR DESCRIPTION
**Pull request by degenaro**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [ ] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by degenaro** [comment]
Note: This PR depends on PR #1257

**Review by enikonovad — APPROVED** [review]
LGTM

**Comment by degenaro** [comment]
@enikonovad Thx for the review! 

@fsuits Please have a look to see if this will affect you? Do I need to do anything else before merging?

**Comment by fsuits** [comment]
@degenaro This should be ok - I'm already getting rules from the components.  LGTM

**Comment by degenaro** [comment]
@fsuits @enikonovad I resolved a conflict in 1 static file, but now the build fails in places I did not touch??

**Comment by fsuits** [comment]
Hi @degenaro there was a change in flake8 that hit me also and I needed to add warnings to ignore in the pre-commit file.  That update is in my branch, which I hope to merge today.  Once that happens you will be able to pull the changes and it should work then.

**Comment by degenaro** [comment]
@fsuits Thx, will give it a try...

**Pull request merged**
