### PR TITLE
docs: change trestle project references to workspace

### PR DESCRIPTION
**Pull request by AleJo2995**
Signed-off-by: Alejandro Jose Leiva Palomo <alejandro.leiva.palomo@ibm.com>

## Types of changes

- [ ] Hot fix (emergency fix and release)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary

This pull request address changes to replace trestle project to trestle workspace as specified in issue #1043
Closes https://github.com/IBM/compliance-trestle/issues/1043

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by AleJo2995** [comment]
Closes #1276

**Comment by fsuits** [comment]
@AleJo2995 as discussed please use "trestle workspace" instead of "workspace" to make it more clear.

**Comment by fsuits** [comment]
Please check capitilization of Trestle and confirm all workspace have trestle in front.

**Comment by AleJo2995** [comment]
@fsuits done. Please check and review if changes meet requirements

**Review by fsuits — APPROVED** [review]
Nice work - LGTM

**Pull request merged**
