### PR TITLE
Added error checking and enforce 1 to 1 keys in header validation

### PR DESCRIPTION
**Pull request by fsuits**
Signed-off-by: FrankSuits <frankst@au1.ibm.com>

## Types of changes

- \[x] Bug fix (non-breaking change which fixes an issue)
- \[ \] New feature (non-breaking change which adds functionality)
- \[ \] Breaking change (fix or feature that would cause existing functionality to change)
- \[x] My code follows the code style of this project.
- \[ \] My change requires a change to the documentation.
- \[ \] I have updated the documentation accordingly.
- \[x] I have added tests to cover my changes.
- \[x] All new and existing tests passed.
- \[x] All commits are signed-off.

Enforce 1:1 keys in header validation
Added error checking and test for bold header in template
Changed validation text output for easier reading by user

### CODE REVIEW

**Comment by fsuits** [comment]
This is just to show initial progress in md and to see if my change to user output (VALID INVALID) and providing text response when validation passes are ok.

**Comment by fsuits** [comment]
Added header support in gov. folders and checks for symlinks.

**Review by butler54 — CHANGES_REQUESTED** [review]
As discussed offine:
- add functionality such that directory trees can be recursively covered by cov

**Review by butler54 — APPROVED** [review]
LGTM

**Pull request merged**
