### PR TITLE
feat: adds control origination to ssp-filter

### LINKED ISSUE #1361: Allow ssp-filter by control origination
## Issue description / feature objectives

ssp-filter currently allows filtering based on profile, components, and implementation status. It could be useful to filter by control origination to understand and report on which controls apply to the subject system and which are implemented by other parties. 

## Completion Criteria

- [ ] Provide a new optional argument to ssp-filter: 
`trestle author ssp-filter --control-origination -co` with value being a comma-separated list of strings such as: `customer-configured, inherited`
- [ ] Give error if one of the strings is not one of the allowed values for ssp control origination

### PR DESCRIPTION
**Pull request by jpower432**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [X] My code follows the code style of this project.
- [X] Documentation for my change is up to date?
- [X] My PR meets testing requirements.
- [X] All new and existing tests passed.
- [X] All commits are signed-off.

## Summary

This PR adds an optional control origination flag to the trestle author ssp-filter command. This will filter implemented requirements by the control origination property.

This PR also adds corresponding docs changes to update ssp-filter functionality.

Closes #1361

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by AleJo2995** [comment]
Hey @jpower432 . Glad to see this PR in place. As soon as you get ready for review please put me and Vikas as reviewers and we will be more than glad to help you with it. If you have any questions or any assistance I can provide, please do not hesitate to reach me out :)

**Comment by jpower432** [comment]
Thanks @AleJo2995! This is ready, but I am not able to add reviewers. Would you be able to re-run the failed jobs on this PR? I believe the original failure was due to a GitHub Actions outage.

**Comment by jpower432** [comment]
@AleJo2995 @vikas-agarwal76 Just wanted to reach out about this PR. I am not able to re-run the failed job for windows, but it looks like it was a pytest internal error. Can you please take a look when you have a chance? Appreciate it!

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Comment by jpower432** [comment]
Thanks @vikas-agarwal76. Wanted to double check with you and @AleJo2995 about requirements around merging. I see that I need to squash the commit. Any other requirements since I am working from a fork? Thanks :)

**Comment by vikas-agarwal76** [comment]
@jpower432 Yes, whenever any branch is merged into develop branch it is "Squash and Merge".
Bur, when we merge develop branch into main to make a release then it is "Merge Commit".

**Pull request merged**
