### PR TITLE
fix: log warning for duplicate part ids when writing markdown from json

### PR DESCRIPTION
**Pull request by srmamit**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by AleJo2995** [comment]
Hi @srmamit . Just looking at the PR i see is not yet done. But please make sure that pr title is starting with lower case not with upper case, that´s why the check is failing. And then, please make sure you mark the checks accordingly before merging the PR to develop. Thanks :)

**Review by AleJo2995 — APPROVED** [review]
LGTM

**Comment by AleJo2995** [comment]
@srmamit done. You can go ahead and merge the PR. Please remember to squash and merge. Thanks :)

**Comment by srmamit** [comment]
@AleJo2995 I am not able to merge the PR.. it says only those with write access can merge PR to this repo.

**Pull request merged**
