### PR TITLE
feat: Add ability to use different versions of templates

### LINKED ISSUE #761: trestle author {docs| headers | folders} to allow multiple template versions.
## Issue description / feature objectives
As template enforcer I would like to be able to allow multiple templates within the repository.
In that approach the trestle repositories would be (ideally in a backwards compatible way) redesigned such that there is 'fail over' that is allowed in terms of the templates.

## Caveats / Assumptions
- template versions follow semantic versioning to determine the latest
- 

### Simple
- Templates will either be associated via descending the available semantic versions of the template
- If a template is not a match the latest is always used for reporting errors.
- A strict flag exists to measure against the latest.

## Proposed template structure.
Currently the templates are structured in a way such that:
```
root_folder/.trestle/author/{template_name}/{template_objects}
```
e.g.
for governed docs on a folder called 'ADPs' it would be

```
root_folder/.trestle/author/ADPS/template.md
ADPs/instance_1.md
ADPs/instance_2.md
```
The proposal would be that for backwards compatibility two layouts would be detected:
- The existing structure
```
root_folder/.trestle/author/ADPS/template.md
```
- A new structure which is labeled by a folder(s) which are semantically versioned
```
root_folder/.trestle/author/ADPS/0.0.1/template.md
root_folder/.trestle/author/ADPS/0.0.2/template.md
root_folder/.trestle/author/ADPS/0.1.0/template.md
root_folder/.trestle/author/ADPS/1.0.0/template.md
```
Note that both models can not co-exist.

## Changes that are required
- For each of the operating models a method is required to detect which 'mode' (e.g. version or single version) is used.
   - This will be most complex for 'governed folders' where folders already have meaning. The net result being that semantically versioned folders will be prohibited, unless describing template versions
- Update execution to allow 'fail over' based on the semantic version label.
- Add a '--latest' flag which only allows the latest version, if multiple versions are provided.
- Update testing and documentation.

### PR DESCRIPTION
**Pull request by enikonovad**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary
This change provides a template versioning solution that works as follows:

1. A template version to use is specified when running either `docs`|`folders`|`headers`.
    1. If no version specified the latest version will be used by default.
    2. Otherwise use the templates from the specified version.
2. Backward compatibility.
    1. Version 0.0.1 will be reserved for the template versions prior to this change.
    2. If the old template path is detected (i.e. without the template version), then the filesystem will be updated to the new path with the version.
    3. Upon first run, old template versions prior to this change will be placed to the folder 0.0.1.
    4. If templates have no headers then 0.0.1 version will be used.
3. Versioning organization.
    1. Template and instance version is added to both: in the file system (via path) and in the headers or metadata.
4. Instance version validation.
    1. Markdown:
        1. When validating the instance the header will be used to validate the version by checking both `Version` and `x-trestle-template-version`
    2. Drawio:
        1. When validating the instance the metadata will be used to validate the version by checking both `Version` and `x-trestle-template-version`

Validating old trestle workspace after this change will result in the following structure:
```
.trestle
- author
-- __global__
--- 0.0.1
---- {old_templates}
-- task_docs or task_headers or task_folders
--- 0.0.1
---- {old_templates}
```

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

Closes #761

### CODE REVIEW

**Comment by butler54** [comment]
I'm getting some strange log errors if I run the following:
```bash
mkdir trestle_test
cd trestle_test
trestle init
trestle author docs setup -tn my_task
trestle author docs create-sample -tn my_task
```
The last operation gets the following message that does not make much sense to me:
```No templates outside of the version folders.``` with no other context.

**Comment by enikonovad** [comment]
This message is okay, the `No templates outside of the version folders.` is the information message that there are no "old templates". I should probably move it to debug level though.

**Comment by butler54** [comment]
[trestle_test.zip](https://github.com/IBM/compliance-trestle/files/7503407/trestle_test.zip)

I attached a test trestle repo here where I created two templates (0.1.0) and (0.0.1).

0.1.0 does not seem to get recognised:
```
trestle author docs validate -tn my_task --template-version=0.1.0 -v
2021-11-09 20:04:50,312 trestle.core.commands.author.common:71 ERROR: Specified template version is invalid, please select other version.
```,
or 
```
trestle author docs create-sample -tn my_task --template-version=0.1.0 -v
2021-11-09 20:05:29,233 trestle.core.commands.author.common:71 ERROR: Specified template version is invalid, please select other version.
```
This behaves as expected:
```
trestle author docs validate -tn my_task --template-version=0.0.1   
No templates outside of the version folders.
New headers of level 1 were added to the markdown instance: /Users/chris/Desktop/trestle_test/my_task/sample_010_template.md. 
INVALID: my_task/sample_010_template.md
VALID: my_task/sample.md
VALID: my_task/my_task_000.md
VALID: my_task/my_task_001.md
VALID: my_task/my_task_002.md
```

However this does not 
```
trestle author docs validate -tn my_task                         
No templates outside of the version folders.
New headers of level 1 were added to the markdown instance: /Users/chris/Desktop/trestle_test/my_task/sample_010_template.md. 
INVALID: my_task/sample_010_template.md
VALID: my_task/sample.md
VALID: my_task/my_task_000.md
VALID: my_task/my_task_001.md
VALID: my_task/my_task_002.md
```
Under this scenario where a template version was not passed I would expect an optimistic test of the available templates.

**Review by butler54 — CHANGES_REQUESTED** [review]
Please look at the comments in the body of the PR. I think that @jayhawk87's expectations and mine might differ slightly w.r.t. the CLI behaviour, however, there definitely seems to be an issue for me on OSX when I try from scratch.

**Comment by jayhawk87** [comment]
@butler54 - what you've got in your example is certainly not what the code expects - but I view that as showing places where this PR is missing changes and tests that it needs - I'm thinking through how to address these gaps.

**Comment by enikonovad** [comment]
Given the current implementation the two cases above are expected behaviour. For the second case if no version is specified then it will default to the latest template version _in Trestle resources_ (which in this case `0.0.1`). 

As of the first case:

In my understanding, template versions is something that is coming from Trestle (hence `x-trestle-header-version`). The user is expected to generate the folders inside of the `.trestle/author` via execution of the `setup` command. And then modify it as they wish. Therefore the check on the available version is done by checking what templates versions are available inside the Trestle internal resource folder not the workspace. Since currently the only version inside Trestle is `0.0.1` a call for all other templates versions will fail. In this way, versioning is entirely managed by Trestle.

On the other hand, if we would like to put template versioning in user's hands then I can modify the code slightly to do the check on what versions are available inside `.trestle/author/{task}` folder rather than in Trestle resources.  In this case, upon the `setup` command execution, user can specify _any_ version and Trestle will create that folder with a generic template in it.

From my perspective, I think both ways are valid. Former restricts users in the number of possible template versions and ensures that users use `setup` to create a task. Later gives more freedom to the users and allows them to manually create different template versions for each task. 

If the later is what you had in mind, I can slightly modify the code to reflect that.

**Comment by enikonovad** [comment]
@butler54 @jayhawk87 I have modified the logic for the template versioning.

Overall the logic is now as follows:

1) User can create any version of the template for the task as follows:
> trestle author docs setup -tn -tv=11.12.123

This will initialize a folder with a template that has 'x-trestle-version-template' set to the provided version.

2) User then can select which template to use to create samples:
> trestle author docs create-sample -tn my_task -tv=11.12.123

This will create a sample task with header or metadata set to a version of a template.

3) Finally user can validate samples for selected template:
> trestle author docs validate -tn my_task_3 -tv=0.0.23 -hv
```      
Set template version to 0.0.23.
Versions of the template 0.0.23 and instance 11.12.123 are different
YAML header mismatch between template /Users/enikon/Projects/trestle_test/.trestle/author/my_task_3/0.0.23/template.md and instance /Users/enikon/Projects/trestle_test/my_task_3/my_task_3_001.md
INVALID: my_task_3/my_task_3_001.md
VALID: my_task_3/my_task_3_000.md
```

4) if no version provided the latest version for this task will be used:
> trestle author docs validate -tn my_task_3 -tv=0.0.23 -hv
```
Set template version to 11.12.123.
VALID: my_task_3/my_task_3_001.md
Versions of the template 11.12.123 and instance 0.0.23 are different
YAML header mismatch between template /Users/enikon/Projects/trestle_test/.trestle/author/my_task_3/11.12.123/template.md and instance /Users/enikon/Projects/trestle_test/my_task_3/my_task_3_000.md
INVALID: my_task_3/my_task_3_000.md
```

5) if folder contains any old templates without the version (i.e. prior to this change) they will be moved to the folder with version `0.0.1`

**Comment by enikonovad** [comment]
Tested for the examples above and the output is now as expected:

```
trestle author docs validate -tn my_task --template-version=0.0.1 -v
Set template version to 0.0.1.
New headers of level 1 were added to the markdown instance: /Users/enikon/Projects/trestle_test/my_task/sample_010_template.md. 
INVALID: my_task/sample_010_template.md
VALID: my_task/sample.md
VALID: my_task/my_task_000.md
VALID: my_task/my_task_001.md
VALID: my_task/my_task_002.md
```

and for other 

```
trestle author docs validate -tn my_task
Set template version to 0.1.0.
VALID: my_task/sample_010_template.md
Headings in the instance: /Users/enikon/Projects/trestle_test/my_task/sample.md were removed.
INVALID: my_task/sample.md
Headings in the instance: /Users/enikon/Projects/trestle_test/my_task/my_task_000.md were removed.
INVALID: my_task/my_task_000.md
Headings in the instance: /Users/enikon/Projects/trestle_test/my_task/my_task_001.md were removed.
INVALID: my_task/my_task_001.md
Headings in the instance: /Users/enikon/Projects/trestle_test/my_task/my_task_002.md were removed.
INVALID: my_task/my_task_002.md
```

**Comment by butler54** [comment]
Okay I think I have one more request. I think that validate needs to be able to take multiple template versions for validation.

Why: 
If I have a repo I need to be able to ask 'does my document validate with ANY of my acceptable versions'. The biggest issues I have here is when we do this with A CI pipeline the only useful flag we have for pass failure is the return code.

E.g. this can't be a human reading that A & B use version 0.0.1 and C uses 0.1.0 and that is okay. It needs to be the output of the command?

**Comment by jayhawk87** [comment]
@butler54 - I agree with you because I'm thinking through what happens when I recurse through a document tree ...

**Review by butler54 — APPROVED** [review]

**Pull request merged**
